baseurl = "//blog.urandom.team"
languageCode = "ja-jp"
title = "urandom"

pygmentsUseClasses=true

[params]
    hideShareOptions = true

[markup.goldmark.renderer]
    unsafe = true

[markup.highlight]
    lineNos = true
    style = "solarized-dark256"